FROM ubuntu as builder

WORKDIR /app

RUN TZ=America/New_York && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    DEBIAN_FRONTEND=noninteractive && \
    apt-get update && apt-get upgrade -y && apt-get autoremove -y && \ 
    apt-get install make git zlib1g-dev libssl-dev gperf php-cli cmake clang libc++-dev libc++abi-dev -y && \
    cd /app && git clone https://github.com/tdlib/td.git

