FROM ubuntu as builder

WORKDIR /app

COPY build-td-web.sh /app/build-td-web.sh
RUN sed -i -e 's/\r$//' /app/build-td-web.sh
RUN chmod +x build-td-web.sh
RUN ./build-td-web.sh

FROM alpine
WORKDIR /app
COPY --from=builder /app/td/example/web/tdweb/dist ./dist
COPY --from=builder /app/td/example/web/tdweb/src ./src
