FROM ubuntu as builder

WORKDIR /app

COPY build-tdlib.sh /app/build-tdlib.sh
RUN sed -i -e 's/\r$//' /app/build-tdlib.sh
RUN chmod +x build-tdlib.sh
RUN ./build-tdlib.sh

FROM alpine
WORKDIR /app
COPY --from=builder /app/td/tdlib ./tdlib