name: 'Prepare Environment'
description: 'Setup environment and download container image'
inputs:
  token:
    description: 'Github token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Container
      run: |
        echo "${{ inputs.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker pull ghcr.io/${{ github.actor }}/vstools:latest
