name: Hourly KMS Health Check

on:
  # schedule:
  #   - cron: "0 * * * *"   # Runs every hour at minute 0
  workflow_dispatch:       # Allows manual trigger

jobs:
  check-site:
    runs-on: ubuntu-latest

    steps:
      - name: Check website availability
        run: |
          URL="https://spotless-aveline-kishan-2457d23a.koyeb.app/"
          echo "Checking $URL"
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" "$URL")
          echo "Status code: $STATUS"

          URL="https://www.fenilcomics.com/"
          echo "Checking $URL"
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" "$URL")
          echo "Status code: $STATUS"
