name: build linux-buildtools

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Build the Docker image
      run: |
        docker build -t ghcr.io/pfeux/linuxtools:latest -f Dockerfile.linuxtools .
        echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u pfeux --password-stdin
        docker push ghcr.io/pfeux/linuxtools:latest
  
    - name: Commit code
      shell: bash
      run: |
        git fetch
        git pull
        echo "$(date -u)" >> linuxtools.log
        git config --global user.name "Kishan"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add linuxtools.log
        git commit -m "Update linuxtools.log" || echo "no change to commit"
        git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
