name: tdbuilder for tdlib for windows

on:
  schedule:
    - cron: '0 1 1 * *'
    
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build -t ttl.sh/tdlib-win:24h -f Dockerfile.tdlib-win .
        docker push ttl.sh/tdlib-win:24h
