name: tdbuilder for tdweb

on:
  # schedule:
  #   - cron: '0 2 * * 2'

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.13.0
      with:
        context: .
        file: Dockerfile.tdweb
        push: true
        tags: ghcr.io/${{ github.actor }}/tdbuilder-tdweb:latest

    - name: Commit code
      shell: bash
      run: |
        git fetch
        git pull
        echo "$(date -u)" > tdlib-web.log
        git config --global user.name "Kishan"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add tdlib-web.log
        git commit -m "Update tdlib-web.log" || echo "no change to commit"
        git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Delete tdbuilder-tdweb older packages
      run: |
        owner="pfeux"
        package="tdbuilder-tdweb"
        
        versions=$(gh api "users/$owner/packages/container/$package/versions" --paginate)
        to_delete=$(echo "$versions" | jq -r 'sort_by(.created_at) | reverse | .[3:] | .[].id')

        for id in $to_delete; do
          echo "Deleting version ID: $id"
          gh api --method DELETE "users/$owner/packages/container/$package/versions/$id"
        done

      shell: bash
      env:
        GH_TOKEN: ${{ secrets.TOKEN }}
