name: tdbuilder for tdserver

on:
  schedule:
    - cron: '0 5 1 * *'
    
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.tdserver --tag ttl.sh/tdbuilder-tdserver:24h
        docker push ttl.sh/tdbuilder-tdserver:24h
