name: tdbuilder for tdlib for linux

on:
  schedule:
    - cron: '0 5 * * 5'
    
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.13.0
      with:
        context: .
        file: Dockerfile.tdlib-linux
        push: true
        tags: ghcr.io/${{ github.actor }}/tdlib-linux:latest    
