name: tdbuilder for tdserver

on:
  schedule:
    - cron: '0 5 1 * *'
    
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: Dockerfile.tdserver
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
