name: build vs-buildtools

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Build the Docker image
      run: |
        docker build -t ghcr.io/pfeux/vstools:latest -f Dockerfile.vstools .
        echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u pfeux --password-stdin
        docker push ghcr.io/pfeux/vstools:latest

    - name: Commit code
      shell: bash
      run: |
        git fetch
        git pull
        echo "$(date -u)" > vstools.log
        git config --global user.name "Kishan"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add vstools.log
        git commit -m "Update vstools.log" || echo "no change to commit"
        git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Delete vstools older packages
      run: |
        $owner = "pfeux"
        $package = "vstools"
        
        $versions = gh api users/$owner/packages/container/$package/versions --paginate | ConvertFrom-Json
        $sorted = $versions | Sort-Object -Property created_at -Descending
        $toDelete = $sorted | Select-Object -Skip 3
        foreach ($version in $toDelete) {
          $id = $version.id
          Write-Host "Deleting version Id: $id"
          gh api --method DELETE "users/$owner/packages/container/$package/versions/$id"
        }
      shell: pwsh
      env:
        GH_TOKEN: ${{ secrets.TOKEN }}
