name: build vs-buildtools

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Build the Docker image
      run: |
        docker build -t ghcr.io/pfeux/vstools:latest -f Dockerfile.vstools .
        echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u pfeux --password-stdin
        docker push ghcr.io/pfeux/vstools:latest
